apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: knative-demo-buildconfig
objects:
- apiVersion: eventing.knative.dev/v1
  kind: Broker
  metadata:
    name: default
    namespace: ${APP_NAMESPACE}
- apiVersion: eventing.knative.dev/v1
  kind: Trigger
  metadata:
    name: event-display-trigger
    namespace: ${APP_NAMESPACE}
  spec:
    broker: default
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: event-display
- apiVersion: eventing.knative.dev/v1
  kind: Trigger
  metadata:
    name: dispatcher-trigger
    namespace: ${APP_NAMESPACE}
  spec:
    broker: default
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: dispatcher-go
- apiVersion: sources.knative.dev/v1
  kind: SinkBinding
  metadata:
    name: producer-binding
    namespace: ${APP_NAMESPACE}
  spec:
    subject:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: producer-python
    sink:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        name: default
        namespace: ${APP_NAMESPACE}
- apiVersion: sources.knative.dev/v1
  kind: SinkBinding
  metadata:
    name: dispatcher-binding
    namespace: ${APP_NAMESPACE}
  spec:
    subject:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: dispatcher-go
    sink:
      ref:
        apiVersion: messaging.knative.dev/v1
        kind: Channel
        name: event-channel
        namespace: ${APP_NAMESPACE}
- apiVersion: messaging.knative.dev/v1
  kind: Channel
  metadata:
    name: event-channel
    namespace: ${APP_NAMESPACE}
- apiVersion: messaging.knative.dev/v1
  kind: Subscription
  metadata:
    name: loader-subscription
    namespace: ${APP_NAMESPACE}
  spec:
    channel:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: event-channel
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: loader-quarkus
- apiVersion: messaging.knative.dev/v1
  kind: Subscription
  metadata:
    name: event-display-subscription
    namespace: ${APP_NAMESPACE}
  spec:
    channel:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: event-channel
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: event-display
parameters:
- description: App namespace
  from: '[A-Z0-9]{8}'
  generate: expression
  name: APP_NAMESPACE
labels:
  app: demo
  layer: infra